apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app-container
        image: monopole/hello:1
        command: ["/hello",
                  "--port=80",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 80
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: map
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: map
              key: enableRisky
